version: '3.7'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}
      CLARIFAI_API_KEY: ${CLARIFAI_API_KEY}
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    build: ./postgres
    environment:
          POSTGRES_USER: ${POSTGRES_USERNAME}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB_NAME}
          POSTGRES_HOST: postgres
    ports:
      - "5432:5432"